CONFERENCES = [
    (1, "AAC", "American Athletic Conference", "American", 1979),
    (1, "ACC", "Atlantic Coast Conference", "ACC", 1953),
    (1, "BIG12", "Big 12 Conference", "Big 12", 1994),
    (1, "BIG10", "Big Ten Conference", "Big Ten", 1896),
    (1, "C-USA", "Conference USA", "Conference USA", 1995),
    (1, "FBS-IND", "FBS Independents", "FBS Independents", None),
    (1, "MAC", "Mid-American Conference", "Mid-American", 1946),
    (1, "MWC", "Mountain West Conference", "Mountain West", 1999),
    (1, "PAC12", "Pac-12 Conference", "Pac-12", 1959),
    (1, "SEC", "Southeastern Conference", "SEC", 1932),
    (1, "SBLT", "Sun Belt Conference", "Sun Belt", 1976),
    (2, "BSKY", "Big Sky Conference", "Big Sky", 1963),
    (2, "BIGSTH", "Big South Conference", "Big South", 1983),
    (2, "CAA", "Colonial Athletic Association", "CAA", 1979),
    (2, "FCS-IND", "FCS Indepenents", "FCS Independents", None),
    (2, "GWST", "Great West Conference", "Great West", 2004),
    (2, "IVY", "The Ivy League", "Ivy", 1954),
    (2, "MEAC", "Mid-Eastern Athletic Conference", "MEAC", 1970),
    (2, "MVC", "Missouri Valley Conference", "Missouri Valley", 1907),
    (2, "NEC", "Northeast Conference", "Northeast", 1981),
    (2, "OVC", "Ohio Valley Conference", "Ohio Valley", 1948),
    (2, "PAT", "Patriot League", "Patriot League", 1986),
    (2, "PFL", "Pioneer Football League", "Pioneer", 1991),
    (2, "SOCON", "Southern Conference", "So-Con", 1921),
    (2, "SLC", "Southland Conference", "Southland", 1963),
    (2, "SWAC", "Southwestern Athletic Conference", "SWAC", 1920)
]