language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pip install sphinx
  - pytest --cov hatchet
#  - bash ./publish.sh
env:
  global:
  - GH_USER: exleym
  - GH_REPO: Hatchet
  - GH_TOKEN: $GITHUB_TOKEN
after_success:
  - coveralls
#deploy:
#  provider: elasticbeanstalk
#  access_key_id:
#    secure: "Encrypted <access-key-id>="
#  secret_access_key:
#    secure: "Encypted <secret-access-key>="
#  region: "us-east-1"
#  app: "hatchet"
#  env: "example-app-environment"
#  bucket_name: "the-target-S3-bucket"