language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pip install coveralls
  - pytest --cov hatchet
  - make html
  - touch docs/build/html/.nojekyll
#  - bash ./publish.sh
env:
  global:
  - GH_USER: exleym
  - GH_REPO: Hatchet
  - GH_TOKEN: $GITHUB_TOKEN
after_success:
  - coveralls
deploy:
  provider: pages
  local_dir: docs/build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
#deploy:
#  provider: elasticbeanstalk
#  access_key_id:
#    secure: "Encrypted <access-key-id>="
#  secret_access_key:
#    secure: "Encypted <secret-access-key>="
#  region: "us-east-1"
#  app: "hatchet"
#  env: "example-app-environment"
#  bucket_name: "the-target-S3-bucket"