version: '3.7'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hatchet
  web:
    build: AxeUI/
    ports:
      - 80:80
    environment:
      env: prod

