openapi: "3.0.0"
info:
  title: "Hatchet API"
  version: "v1"
servers:
  - url: 'http://localhost:5000/api/v1'
    description: default machine
paths:
  /conferences:
    $ref: './swagger/paths/conferences.yml#/conferences'
  /conferences/{conferenceId}:
    $ref: './swagger/paths/conferences.yml#/conferences~1{conferenceId}'
  /conferences/{conferenceId}/divisions:
    $ref: './swagger/paths/conferences.yml#/conferences~1{conferenceId}~1divisions'
  /conferences/{conferenceId}/members:
    $ref: './swagger/paths/conferences.yml#/conferences~1{conferenceId}~1members'
  /divisions:
    $ref: './swagger/paths/divisions.yml#/divisions'
  /divisions/{divisionId}:
    $ref: './swagger/paths/divisions.yml#/divisions~1{divisionId}'
  /divisions/{divisionId}/members:
    $ref: './swagger/paths/divisions.yml#/divisions~1{divisionId}~1members'
  /teams:
    $ref: './swagger/paths/teams.yml#/teams'
  /teams/{teamId}:
    $ref: './swagger/paths/teams.yml#/teams~1{teamId}'
  /stadiums:
    $ref: './swagger/paths/stadiums.yml#/stadiums'
  /stadiums/{stadiumId}:
    $ref: './swagger/paths/stadiums.yml#/stadiums~1{stadiumId}'
components:
  schemas:
    $ref: './swagger/definitions.yml#/schemas'

